<?php

namespace Database\Seeders;

use App\Models\Diagnostic;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DiagnosticoSeeder extends Seeder
{
    public function run(): void
    {
        $diagnosticos = [
            'Chequeo pulmonar',
            'No patologia pulmonar',
            'Asma leve',
            'Asma leve controlada',
            'Asma leve parcialmente controlada',
            'Asma leve no controlada',
            'Asma moderada',
            'Asma severa',
            'Asma intermitente',
            'EPOC GOLD 1',
            'EPOC GOLD 2',
            'EPOC GOLD 3',
            'EPOC GOLD 4',
            'EPOC GRUPO A',
            'EPOC GRUPO B',
            'EPOC GRUPO C',
            'EPOC GRUPO D',
            'Covid leve',
            'Covid moderado',
            'Covid severo',
            'Covid crítico',
            'Control postcovid leve',
            'Control postcovid moderado',
            'Control postcovid severo',
            'Control postcovid crítico',
            'Dorsalgia postcovid',
            'Cefalea postcovid',
            'Rinitis postcovid',
            'Rinitis alérgica',
            'Goteo postnasal',
            'Fibrosis pulmonar',
            'Neumonitis por hipersensibilidad',
            'Neumonía intersticial no específica',
            'Neumonia bacteriana',
            'Neumonia viral',
            'Neumonia parasitaria',
            'Micosis pulmonar',
            'Aspergiloma',
            'Aspergilosis pulmonar',
            'Neumonia intersticial descamativa',
            'Tuberculosis pulmonar sensible',
            'Tuberculosis monoresistente a isoniacida',
            'Tuberculosis multidrogorresistente',
            'Tuberculosis extremadamente resistente',
            'Tuberculosis pleural',
            'Tuberculosis ganglionar',
            'Tuberculosis mamaria',
            'Secuela pulmonar',
            'Bronquiectasia leve',
            'Bronquiectasia moderada',
            'Bronquiectasia severa',
            'Fibrotorax',
            'Nodulo pulmonar',
            'Masa pulmonar',
            'Adenopatia mediastinal',
            'Cáncer de pulmón  I',
            'Cáncer de pulmón  II',
            'Cáncer de pulmón  III',
            'Cáncer de pulmón  IV',
            'Metástasis  pulmona',
            'Metástasis de primario no pulmonar',
            'Metástasis  extrapulmonar',
            'Fibrosis pulmonar postcovid',
            'Dorsalgia no pulmonar',
            'Faringitis aguda',
            'Faringitis crónica',
            'Amigdalitis aguda',
            'Amigdalitis crónica',
            'Laringitis aguda',
            'Laringitis crónica',
            'Estenosis subglótica',
            'Estenosis traqueal',
            'Bronquitis aguda',
            'Bronquitis crónica',
            'Bronquiolitis',
            'Enfisema pulmonar',
            'Bula pulmonar',
            'Neumotorax primario',
            'Neumotorax secundario',
            'Fibrosis Pulmonar Progresiva (J84.9)',
            'Pulmon atrapado',
            'Fibrosis quistica',
            'Congestion pulmonar',
            'Diabetes',
            'Hipertensión arterial',
            'Insuficiencia cardíaca',
            'Arritmia cardíaca',
            'Gastritis',
            'Úlcera gástrica',
            'Insuficiencia respiratoria aguda',
            'Insuficiencia respiratoria crónica',
            'Histoplasmosis',
            'Criptocococis pulmonar',
            'Hemosiderosis pulmonar',
            'Linfangioleiomiomatosis',
            'Sarcoidosis',
            'Histiocitosis celulas lnagerhans',
            'Neumonía criptogenica',
            'Neumonía lipoidea',
            'Enfermedad de reflujo gastroesofágico',
            'Pirosis',
            'Traqueitis',
            'Dengue',
            'Neumonectomía derecha ',
            'Neumonectomía izquierda ',
            'EPID  en estudio ',
            'EPID leve ',
            'EPID moderado ',
            'EPID severo ',
            'Asma (prueba terapeútica)',
            'ASMA / EPOC ',
            'Artritis Reumatoide',
            'L.E.S',
            'Neumonitis por Hipersensibilidad Fibrosante',
            'Neumonitis por Hipersensibilidad No Fifrosante',
            'Dolor abdominal ',
            'Efusión pleural derecha ',
            'Efusión pleural izquierda',
            'Esclerodermia ',
            'Tuberculosis miliar',
            'Tuberculosis Sistémica',
            'Tuberculosis Pleuroparenquimal ',
            'Tuberculosis Pulmonar',
            'Control post neumonía ',
            'Hidroneumotorax izquierdo',
            'Hipertensión Arterial Pulmonar (sospecha) ',
            'Secuela pulmonar Leve Post Infecciosa ',
            'Secuela Pulmonar moderada Post Infecciosa',
            'Secuela Pulmonar Severa Post Infecciosa',
            'Bronquiectasia',
            'Asma (sospecha)',
            'EPID (sospecha)',
            'Candidiasis Orofaringea',
            'Otitis Media Aguda',
            'Otitis Externa',
            'Tos por medicamento',
            'EPOC GOLD 1 GRUPO A',
            'SIND. FEBRIL',
            'Asma moderada controlada',
            'Asma moderada parcialmente controlada',
            'Asma moderada no controlada',
            'Asma severa controlada',
            'Asma severa parcialmente controlada',
            'Asma severa no controlada',
            'EPOC GOLD 1 GRUPO B',
            'Vertigo',
            'Líquidos restringidos',
            'Deshidratación',
            'Infección viral aguda',
            'Efusión pleural',
            'Neumomediastino no resuelto',
            'Disfagia funcional',
            'Tromboembolismo Pulmonar',
            'Epistaxis',
            'Caries dental',
            'EPOC GOLD 4 GRUPO C',
            'Divertículo traqueal',
            'Neumomediastino resuelto',
            'Atelectasia post quirúrgica',
            'Taquicardia Paroxística',
            'Contusión pulmonar',
            'Neumonía de lenta resolución',
            'Tuberculosis Pulmonar (sospecha)',
            'Neumonía',
            'Obesidad grado I',
            'Bronquitis Eosinofílica',
            'Fibroenfisema pulmonar',
            'Fibromialgia',
            'Fractura costal',
            'Diaforesis',
            'Insuficiencia Respiratoria Crónica con retención d',
            'Hernia diafragmática',
            'Neumotórax derecho crónico',
            'Hidroneumotorax derecho crónico',
            'Secuela Pulmonar Post Tuberculosis',
            'Atrapamiento pulmonar',
            'Infarto Cerebral',
            'Enfermedad Renal Cronica en Dialisis',
            'Ansiedad',
            'Crisis Asmática Leve',
            'Crisis Asmática Moderada',
            'Crisis Asmática Severa',
            'Suspiro/ Fatiga',
            'Tic Nervioso',
            'Dolor costal',
            'Condrosarcoma  (presuntivo)',
            'Osteosarcoma (presuntivo)',
            'Condrosarcoma costal (presuntivo)',
            'Ansiedad / Depresión',
            'Tuberculosis pulmonar ( por tomografía)',
            'Nódulo pulmonar calcificado',
            'Efusión pleural maligna (sospecha)',
            'Hemoptisis',
            'Hepatopatia Cronica',
            'Infarto Pulmonar',
            'Consolidación pulmonar (Dc NM Pulmón)',
            'Secuela ACV',
            'Disfagia',
            'Costocondritis',
            'Fistula Traqueoesofagica',
            'OPRESION DE PECHO',
            'EPOC GOLD 3 GRUPO E',
            'Fibrosos Pulmonar Progresiva',
            'Fibrosis Pulmonar Progresiva',
            'MICOFENOLATO mofetil (500 MG) # 30 tab',
            'Fibrosis Pulmonar PostCovid Incipiente',
            'Efusión Pericárdica (Dc TBC)',
            'ASMA Inducida por el ejercicio',
            'Vasculitis Pulmonar',
            'Contacto Tuberculosis',
            'GESTACION 1 TRIMESTRE',
            'ABSCESO PULMONAR',
            'INFECCION URINARIA',
            'Traumatismo craneal',
            'Tuberculosis Laríngea',
            'Diarrea',
            'Pectus Excavatum',
            'Impétigo contagioso',
            'Sind. Lóbulo medio',
            'Neumoconiosis',
            'Tumor Laríngeo',
            'EPOC N/E',
            'TUMOR MEDIASTINAL',
            'LInfoma Mediastinal ( sospecha)',
            'FIBROSIS PULMONAR IDIOPATICA (sospecha)',
            'SIND. SUPERPOSICION',
            'Fisura Costal',
            'INFORME TOMOGRAFIA PULMONAR:',
            'CONCLUSIÓN:',
            'MIcobacterium No Tuberculosis',
            'Enfermedad mixta del Tejido Conectivo',
            'PAQUIPLEURITIS ( en estudio)',
            'Quiste Hidatídico Complicado',
            'Evaluación Pulmonar Normal',
            'EPOC GRUPO E',
            'Fibrosis Pulmonar Idiopática',
            'Gestación III trimestre',
            'Dc Empiema Pleural',
        ];

        foreach ($diagnosticos as $diagnostico) {
            Diagnostic::create(['descripcion' => $diagnostico]);
        }
    }
}