<?php

namespace Database\Seeders;

use App\Models\Occupation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OcupacionSeeder extends Seeder
{
    public function run(): void
    {
        $ocupaciones = [
            'PALMICULTOR (A)',            
            'TRABAJADOR INDEPENDIENTE', 
            'DOCENTE / PROFESOR (A)', 
            'AGRICULTOR (A)', 
            'COMERCIANTE', 
            'ESTUDIANTE', 
            'TEC. ENFERMERÍA',
            'LIC. ENFERMERÍA ', 
            'MÉDICO / CIRUJANO', 'SUBOFICIAL PNP', 
            'MECÁNICO', 
            'CAMBISTA', 
            'CONSTRUCTOR / OBRERO / ALBAÑIL',
            'NOTARIO',
            'ABOGADO (A)', 
            'JUBILADO (A)', 
            'ARTESANO (A) / CARPPINTERO / ALFARERO (A)',
            'ODONTÓLOGO / TEC. ODONTÓLOGO ', 
            'GINECÓLOGO (A)', 
            'TRANSPORTISTA ', 
            'PERSONAL DE LIMPIEZA',
            'ING. SISTEMAS / INFORMÁTICO / TELECOMUNICACIONES', 
            'ING. CIVIL', 
            'MILITAR', 
            'ECONOMISTA', 
            'ADMINISTRADOR (A)', 
            'MODISTA',
            'EMPRESARIO (A)', 
            'EMPLEADO PÚBLICO', 
            'OFICINISTA', 
            'COCINERO (A) / ASADOR (A)', 
            'OPERADOR DE MAQUINARIA ', 
            'ING. FORESTAL / AMBIENTAL / AGRÓNOMO',
            'ARQUITECTO (A)', 
            'TEC. MECÁNICO / ELECTRICISTA', 
            'SECRETARIA / ASISTENTE', 
            'GANADERO', 
            'COMUNICADOR / LOCUTOR ', 
            'PINTOR', 
            'PELUQUERO / ESTILISTA ', 
            'PSICÓLOGO (A)', 
            'GERENTE', 
            'ING. QUÍMICO / QUÍMICO / PETROQUÍMICO', 
            'RELIGIOSO (A) / MISIONERO', 
            'BIÓLOGO', 
            'TEC. ELECTRICISTA ', 
            'HERPETÓLOGO', 
            'TEC. COMPUTACIÓN / INFORMÁTICO', 
            'ING. NAVAL / PESQUERO', 
            'ASESOR DE NEGOCIOS / VENTAS', 
            'MOTOTAXISTA / DELIVERISTA ',
            'COSMETOLOGO (A) / MANICURISTA',
            'LABORATORISTA',
            'VETERINARIO / ZOOTÉCNICO',
            'WACHIMAN / GUARDIA DE SEGURIDAD',
            'AZAFATA',
            'VENDEDOR / CAJERO',
            'NO LABURA',
            'MÚSICO / CANTANTE ',
            'ASISTENTE SOCIAL ',
            'POLICÍA EN RETIRO',
            'PUBLICISTA / DISEÑADOR GRÁFICO',
            'OFICIAL EJÉRCITO / PNP / FAP / MGP',
            'DOCENTE JUBILADO',
            'AMBULANTE',
            'SOLDADOR / HERRERO',
            'SASTRE / COSTURERO (A)',
            'ING. INDUSTRIAL / AGROINDUSTRIAL',
            'AUXILIAR EN EDUCACIÓN',
            'ESTIBADOR',
            'TEC. ELÉCTRICO / ELECTRICISTA',
            'AUDITOR',
            'PERIODISTA / REPORTERO (A)',
            'DEPORTISTA / FUTBOLISTA / ATLETA',
            'ENTRENADOR / GIMNASTA',
            'ARTISTA / COMEDIANTE',
            'SOCIÓLOGO',
            'QUIROPRÁCTICO ',
            'ING. MECÁNICO',
            'CIENCIAS DE LA SALUD / NUTRICIONISTA',
            'TEC. CONSTRUCCIÓN CIVIL',
            'BIBLIOTECARIO',
            'BANQUERO',
            'JOYERO / RELOJERO',
            'OPTÓMETRO ',
            'PESCADOR',
            'CONTADOR (A)',
            'CESANTE',
            'TEC. CONTADOR',
            'GEÓLOGO (A)',
            'AMA DE CASA',
            'INVESTIGADOR (A)',
            'TECNÓLOGO',
            'MAYOR DOMO / AMA DE LLAVES',
            'SUBOFICIAL EP / FAP / MGP',
            'BIÓLOGO / MICROBIÓLOGO',
            'OFTALMÓLOGO',
            'PODÓLOGO',
            'ANESTESIÓLOGO (A)',
            'MINERO (A)',
            'PANADERO / PASTELERO',
            'PRESENTADOR TV',
            'CEO',
            'FILÓSOFO (A)',
            'MALABARISTA',
            'URÓLOGO',
            'MESERO / CAMARERO / MOZO',
            'GERIATRA',
            'PEDIATRA',
            'NEUMÓLOGO',
            'MÉDICO GENERAL',
            'QUÍMICO FARMACÉUTICO',
            'MOCHILERO',
            'SIN OCUPACIÓN',
            'ACTOR / ACTRIZ / MODELO',
            'CARDIÓLOGO',
            'ING. ELECTRÓNICO',
            'OBSTETRA',
            'POLICÍA',
            'BOMBERO',
            'MÉDICO /OTORRINOLARINGÓLOGO',
            'OPTOMETRISTA PEDIATRICO',
            'CHEF / BARTENDER',
            'BARMAN',
            'ENTOMÓLOGO (A)',
            'SACERDOTE',
            'GANADERO / RANCHERO',
            'MÉDICO / NEUMÓLOGO',
            'ING. COMERCIAL',
            'ING. INDUSTRIAL',
        ];

        foreach ($ocupaciones as $item) {
            Occupation::create([
                'descripcion' => $item,
            ]);
        }
    }
}
