<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UbigeoProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
        $datos = [
            ['id' => '0101', 'nombre_provincia' => 'CHACHAPOYAS', 'department_id' => '01'],
            ['id' => '0102', 'nombre_provincia' => 'BAGUA', 'department_id' => '01'],
            ['id' => '0103', 'nombre_provincia' => 'BONGARÁ', 'department_id' => '01'],
            ['id' => '0104', 'nombre_provincia' => 'CONDORCANQUI', 'department_id' => '01'],
            ['id' => '0105', 'nombre_provincia' => 'LUYA', 'department_id' => '01'],
            ['id' => '0106', 'nombre_provincia' => 'RODRÍGUEZ DE MENDOZA', 'department_id' => '01'],
            ['id' => '0107', 'nombre_provincia' => 'UTCUBAMBA', 'department_id' => '01'],
            ['id' => '0201', 'nombre_provincia' => 'HUARAZ', 'department_id' => '02'],
            ['id' => '0202', 'nombre_provincia' => 'AIJA', 'department_id' => '02'],
            ['id' => '0203', 'nombre_provincia' => 'ANTONIO RAYMONDI', 'department_id' => '02'],
            ['id' => '0204', 'nombre_provincia' => 'ASUNCIÓN', 'department_id' => '02'],
            ['id' => '0205', 'nombre_provincia' => 'BOLOGNESI', 'department_id' => '02'],
            ['id' => '0206', 'nombre_provincia' => 'CARHUAZ', 'department_id' => '02'],
            ['id' => '0207', 'nombre_provincia' => 'CARLOS FERMÍN FITZCARRALD', 'department_id' => '02'],
            ['id' => '0208', 'nombre_provincia' => 'CASMA', 'department_id' => '02'],
            ['id' => '0209', 'nombre_provincia' => 'CORONGO', 'department_id' => '02'],
            ['id' => '0210', 'nombre_provincia' => 'HUARI', 'department_id' => '02'],
            ['id' => '0211', 'nombre_provincia' => 'HUARMEY', 'department_id' => '02'],
            ['id' => '0212', 'nombre_provincia' => 'HUAYLAS', 'department_id' => '02'],
            ['id' => '0213', 'nombre_provincia' => 'MARISCAL LUZURIAGA', 'department_id' => '02'],
            ['id' => '0214', 'nombre_provincia' => 'OCROS', 'department_id' => '02'],
            ['id' => '0215', 'nombre_provincia' => 'PALLASCA', 'department_id' => '02'],
            ['id' => '0216', 'nombre_provincia' => 'POMABAMBA', 'department_id' => '02'],
            ['id' => '0217', 'nombre_provincia' => 'RECUAY', 'department_id' => '02'],
            ['id' => '0218', 'nombre_provincia' => 'SANTA', 'department_id' => '02'],
            ['id' => '0219', 'nombre_provincia' => 'SIHUAS', 'department_id' => '02'],
            ['id' => '0220', 'nombre_provincia' => 'YUNGAY', 'department_id' => '02'],
            ['id' => '0301', 'nombre_provincia' => 'ABANCAY', 'department_id' => '03'],
            ['id' => '0302', 'nombre_provincia' => 'ANDAHUAYLAS', 'department_id' => '03'],
            ['id' => '0303', 'nombre_provincia' => 'ANTABAMBA', 'department_id' => '03'],
            ['id' => '0304', 'nombre_provincia' => 'AYMARAES', 'department_id' => '03'],
            ['id' => '0305', 'nombre_provincia' => 'COTABAMBAS', 'department_id' => '03'],
            ['id' => '0306', 'nombre_provincia' => 'CHINCHEROS', 'department_id' => '03'],
            ['id' => '0307', 'nombre_provincia' => 'GRAU', 'department_id' => '03'],
            ['id' => '0401', 'nombre_provincia' => 'AREQUIPA', 'department_id' => '04'],
            ['id' => '0402', 'nombre_provincia' => 'CAMANÁ', 'department_id' => '04'],
            ['id' => '0403', 'nombre_provincia' => 'CARAVELÍ', 'department_id' => '04'],
            ['id' => '0404', 'nombre_provincia' => 'CASTILLA', 'department_id' => '04'],
            ['id' => '0405', 'nombre_provincia' => 'CAYLLOMA', 'department_id' => '04'],
            ['id' => '0406', 'nombre_provincia' => 'CONDESUYOS', 'department_id' => '04'],
            ['id' => '0407', 'nombre_provincia' => 'ISLAY', 'department_id' => '04'],
            ['id' => '0408', 'nombre_provincia' => 'LA UNIÒN', 'department_id' => '04'],
            ['id' => '0501', 'nombre_provincia' => 'HUAMANGA', 'department_id' => '05'],
            ['id' => '0502', 'nombre_provincia' => 'CANGALLO', 'department_id' => '05'],
            ['id' => '0503', 'nombre_provincia' => 'HUANCA SANCOS', 'department_id' => '05'],
            ['id' => '0504', 'nombre_provincia' => 'HUANTA', 'department_id' => '05'],
            ['id' => '0505', 'nombre_provincia' => 'LA MAR', 'department_id' => '05'],
            ['id' => '0506', 'nombre_provincia' => 'LUCANAS', 'department_id' => '05'],
            ['id' => '0507', 'nombre_provincia' => 'PARINACOCHAS', 'department_id' => '05'],
            ['id' => '0508', 'nombre_provincia' => 'PÀUCAR DEL SARA SARA', 'department_id' => '05'],
            ['id' => '0509', 'nombre_provincia' => 'SUCRE', 'department_id' => '05'],
            ['id' => '0510', 'nombre_provincia' => 'VÍCTOR FAJARDO', 'department_id' => '05'],
            ['id' => '0511', 'nombre_provincia' => 'VILCAS HUAMÁN', 'department_id' => '05'],
            ['id' => '0601', 'nombre_provincia' => 'CAJAMARCA', 'department_id' => '06'],
            ['id' => '0602', 'nombre_provincia' => 'CAJABAMBA', 'department_id' => '06'],
            ['id' => '0603', 'nombre_provincia' => 'CELENDÍN', 'department_id' => '06'],
            ['id' => '0604', 'nombre_provincia' => 'CHOTA', 'department_id' => '06'],
            ['id' => '0605', 'nombre_provincia' => 'CONTUMAZÁ', 'department_id' => '06'],
            ['id' => '0606', 'nombre_provincia' => 'CUTERVO', 'department_id' => '06'],
            ['id' => '0607', 'nombre_provincia' => 'HUALGAYOC', 'department_id' => '06'],
            ['id' => '0608', 'nombre_provincia' => 'JAÉN', 'department_id' => '06'],
            ['id' => '0609', 'nombre_provincia' => 'SAN IGNACIO', 'department_id' => '06'],
            ['id' => '0610', 'nombre_provincia' => 'SAN MARCOS', 'department_id' => '06'],
            ['id' => '0611', 'nombre_provincia' => 'SAN MIGUEL', 'department_id' => '06'],
            ['id' => '0612', 'nombre_provincia' => 'SAN PABLO', 'department_id' => '06'],
            ['id' => '0613', 'nombre_provincia' => 'SANTA CRUZ', 'department_id' => '06'],
            ['id' => '0701', 'nombre_provincia' => 'PROV. CONST. DEL CALLAO', 'department_id' => '07'],
            ['id' => '0801', 'nombre_provincia' => 'CUSCO', 'department_id' => '08'],
            ['id' => '0802', 'nombre_provincia' => 'ACOMAYO', 'department_id' => '08'],
            ['id' => '0803', 'nombre_provincia' => 'ANTA', 'department_id' => '08'],
            ['id' => '0804', 'nombre_provincia' => 'CALCA', 'department_id' => '08'],
            ['id' => '0805', 'nombre_provincia' => 'CANAS', 'department_id' => '08'],
            ['id' => '0806', 'nombre_provincia' => 'CANCHIS', 'department_id' => '08'],
            ['id' => '0807', 'nombre_provincia' => 'CHUMBIVILCAS', 'department_id' => '08'],
            ['id' => '0808', 'nombre_provincia' => 'ESPINAR', 'department_id' => '08'],
            ['id' => '0809', 'nombre_provincia' => 'LA CONVENCIÓN', 'department_id' => '08'],
            ['id' => '0810', 'nombre_provincia' => 'PARURO', 'department_id' => '08'],
            ['id' => '0811', 'nombre_provincia' => 'PAUCARTAMBO', 'department_id' => '08'],
            ['id' => '0812', 'nombre_provincia' => 'QUISPICANCHI', 'department_id' => '08'],
            ['id' => '0813', 'nombre_provincia' => 'URUBAMBA', 'department_id' => '08'],
            ['id' => '0901', 'nombre_provincia' => 'HUANCAVELICA', 'department_id' => '09'],
            ['id' => '0902', 'nombre_provincia' => 'ACOBAMBA', 'department_id' => '09'],
            ['id' => '0903', 'nombre_provincia' => 'ANGARAES', 'department_id' => '09'],
            ['id' => '0904', 'nombre_provincia' => 'CASTROVIRREYNA', 'department_id' => '09'],
            ['id' => '0905', 'nombre_provincia' => 'CHURCAMPA', 'department_id' => '09'],
            ['id' => '0906', 'nombre_provincia' => 'HUAYTARÁ', 'department_id' => '09'],
            ['id' => '0907', 'nombre_provincia' => 'TAYACAJA', 'department_id' => '09'],
            ['id' => '1001', 'nombre_provincia' => 'HUÁNUCO', 'department_id' => '10'],
            ['id' => '1002', 'nombre_provincia' => 'AMBO', 'department_id' => '10'],
            ['id' => '1003', 'nombre_provincia' => 'DOS DE MAYO', 'department_id' => '10'],
            ['id' => '1004', 'nombre_provincia' => 'HUACAYBAMBA', 'department_id' => '10'],
            ['id' => '1005', 'nombre_provincia' => 'HUAMALÍES', 'department_id' => '10'],
            ['id' => '1006', 'nombre_provincia' => 'LEONCIO PRADO', 'department_id' => '10'],
            ['id' => '1007', 'nombre_provincia' => 'MARAÑÓN', 'department_id' => '10'],
            ['id' => '1008', 'nombre_provincia' => 'PACHITEA', 'department_id' => '10'],
            ['id' => '1009', 'nombre_provincia' => 'PUERTO INCA', 'department_id' => '10'],
            ['id' => '1010', 'nombre_provincia' => 'LAURICOCHA ', 'department_id' => '10'],
            ['id' => '1011', 'nombre_provincia' => 'YAROWILCA ', 'department_id' => '10'],
            ['id' => '1101', 'nombre_provincia' => 'ICA ', 'department_id' => '11'],
            ['id' => '1102', 'nombre_provincia' => 'CHINCHA ', 'department_id' => '11'],
            ['id' => '1103', 'nombre_provincia' => 'NASCA ', 'department_id' => '11'],
            ['id' => '1104', 'nombre_provincia' => 'PALPA ', 'department_id' => '11'],
            ['id' => '1105', 'nombre_provincia' => 'PISCO ', 'department_id' => '11'],
            ['id' => '1201', 'nombre_provincia' => 'HUANCAYO ', 'department_id' => '12'],
            ['id' => '1202', 'nombre_provincia' => 'CONCEPCIÓN ', 'department_id' => '12'],
            ['id' => '1203', 'nombre_provincia' => 'CHANCHAMAYO ', 'department_id' => '12'],
            ['id' => '1204', 'nombre_provincia' => 'JAUJA ', 'department_id' => '12'],
            ['id' => '1205', 'nombre_provincia' => 'JUNÍN ', 'department_id' => '12'],
            ['id' => '1206', 'nombre_provincia' => 'SATIPO ', 'department_id' => '12'],
            ['id' => '1207', 'nombre_provincia' => 'TARMA ', 'department_id' => '12'],
            ['id' => '1208', 'nombre_provincia' => 'YAULI ', 'department_id' => '12'],
            ['id' => '1209', 'nombre_provincia' => 'CHUPACA ', 'department_id' => '12'],
            ['id' => '1301', 'nombre_provincia' => 'TRUJILLO ', 'department_id' => '13'],
            ['id' => '1302', 'nombre_provincia' => 'ASCOPE ', 'department_id' => '13'],
            ['id' => '1303', 'nombre_provincia' => 'BOLÍVAR ', 'department_id' => '13'],
            ['id' => '1304', 'nombre_provincia' => 'CHEPÉN ', 'department_id' => '13'],
            ['id' => '1305', 'nombre_provincia' => 'JULCÁN ', 'department_id' => '13'],
            ['id' => '1306', 'nombre_provincia' => 'OTUZCO ', 'department_id' => '13'],
            ['id' => '1307', 'nombre_provincia' => 'PACASMAYO ', 'department_id' => '13'],
            ['id' => '1308', 'nombre_provincia' => 'PATAZ ', 'department_id' => '13'],
            ['id' => '1309', 'nombre_provincia' => 'SÁNCHEZ CARRIÓN ', 'department_id' => '13'],
            ['id' => '1310', 'nombre_provincia' => 'SANTIAGO DE CHUCO ', 'department_id' => '13'],
            ['id' => '1311', 'nombre_provincia' => 'GRAN CHIMÚ ', 'department_id' => '13'],
            ['id' => '1312', 'nombre_provincia' => 'VIRÚ ', 'department_id' => '13'],
            ['id' => '1401', 'nombre_provincia' => 'CHICLAYO ', 'department_id' => '14'],
            ['id' => '1402', 'nombre_provincia' => 'FERREÑAFE ', 'department_id' => '14'],
            ['id' => '1403', 'nombre_provincia' => 'LAMBAYEQUE ', 'department_id' => '14'],
            ['id' => '1501', 'nombre_provincia' => 'LIMA ', 'department_id' => '15'],
            ['id' => '1502', 'nombre_provincia' => 'BARRANCA ', 'department_id' => '15'],
            ['id' => '1503', 'nombre_provincia' => 'CAJATAMBO ', 'department_id' => '15'],
            ['id' => '1504', 'nombre_provincia' => 'CANTA ', 'department_id' => '15'],
            ['id' => '1505', 'nombre_provincia' => 'CAÑETE ', 'department_id' => '15'],
            ['id' => '1506', 'nombre_provincia' => 'HUARAL ', 'department_id' => '15'],
            ['id' => '1507', 'nombre_provincia' => 'HUAROCHIRÍ ', 'department_id' => '15'],
            ['id' => '1508', 'nombre_provincia' => 'HUAURA ', 'department_id' => '15'],
            ['id' => '1509', 'nombre_provincia' => 'OYÓN ', 'department_id' => '15'],
            ['id' => '1510', 'nombre_provincia' => 'YAUYOS ', 'department_id' => '15'],
            ['id' => '1601', 'nombre_provincia' => 'MAYNAS ', 'department_id' => '16'],
            ['id' => '1602', 'nombre_provincia' => 'ALTO AMAZONAS ', 'department_id' => '16'],
            ['id' => '1603', 'nombre_provincia' => 'LORETO ', 'department_id' => '16'],
            ['id' => '1604', 'nombre_provincia' => 'MARISCAL RAMÓN CASTILLA ', 'department_id' => '16'],
            ['id' => '1605', 'nombre_provincia' => 'REQUENA ', 'department_id' => '16'],
            ['id' => '1606', 'nombre_provincia' => 'UCAYALI ', 'department_id' => '16'],
            ['id' => '1607', 'nombre_provincia' => 'DATEM DEL MARAÑÓN ', 'department_id' => '16'],
            ['id' => '1608', 'nombre_provincia' => 'PUTUMAYO', 'department_id' => '16'],
            ['id' => '1701', 'nombre_provincia' => 'TAMBOPATA ', 'department_id' => '17'],
            ['id' => '1702', 'nombre_provincia' => 'MANU ', 'department_id' => '17'],
            ['id' => '1703', 'nombre_provincia' => 'TAHUAMANU ', 'department_id' => '17'],
            ['id' => '1801', 'nombre_provincia' => 'MARISCAL NIETO ', 'department_id' => '18'],
            ['id' => '1802', 'nombre_provincia' => 'GENERAL SÁNCHEZ CERRO ', 'department_id' => '18'],
            ['id' => '1803', 'nombre_provincia' => 'ILO ', 'department_id' => '18'],
            ['id' => '1901', 'nombre_provincia' => 'PASCO ', 'department_id' => '19'],
            ['id' => '1902', 'nombre_provincia' => 'DANIEL ALCIDES CARRIÓN ', 'department_id' => '19'],
            ['id' => '1903', 'nombre_provincia' => 'OXAPAMPA ', 'department_id' => '19'],
            ['id' => '2001', 'nombre_provincia' => 'PIURA ', 'department_id' => '20'],
            ['id' => '2002', 'nombre_provincia' => 'AYABACA ', 'department_id' => '20'],
            ['id' => '2003', 'nombre_provincia' => 'HUANCABAMBA ', 'department_id' => '20'],
            ['id' => '2004', 'nombre_provincia' => 'MORROPÓN ', 'department_id' => '20'],
            ['id' => '2005', 'nombre_provincia' => 'PAITA ', 'department_id' => '20'],
            ['id' => '2006', 'nombre_provincia' => 'SULLANA ', 'department_id' => '20'],
            ['id' => '2007', 'nombre_provincia' => 'TALARA ', 'department_id' => '20'],
            ['id' => '2008', 'nombre_provincia' => 'SECHURA ', 'department_id' => '20'],
            ['id' => '2101', 'nombre_provincia' => 'PUNO ', 'department_id' => '21'],
            ['id' => '2102', 'nombre_provincia' => 'AZÁNGARO ', 'department_id' => '21'],
            ['id' => '2103', 'nombre_provincia' => 'CARABAYA ', 'department_id' => '21'],
            ['id' => '2104', 'nombre_provincia' => 'CHUCUITO ', 'department_id' => '21'],
            ['id' => '2105', 'nombre_provincia' => 'EL COLLAO ', 'department_id' => '21'],
            ['id' => '2106', 'nombre_provincia' => 'HUANCANÉ ', 'department_id' => '21'],
            ['id' => '2107', 'nombre_provincia' => 'LAMPA ', 'department_id' => '21'],
            ['id' => '2108', 'nombre_provincia' => 'MELGAR ', 'department_id' => '21'],
            ['id' => '2109', 'nombre_provincia' => 'MOHO ', 'department_id' => '21'],
            ['id' => '2110', 'nombre_provincia' => 'SAN ANTONIO DE PUTINA ', 'department_id' => '21'],
            ['id' => '2111', 'nombre_provincia' => 'SAN ROMÁN ', 'department_id' => '21'],
            ['id' => '2112', 'nombre_provincia' => 'SANDIA ', 'department_id' => '21'],
            ['id' => '2113', 'nombre_provincia' => 'YUNGUYO ', 'department_id' => '21'],
            ['id' => '2201', 'nombre_provincia' => 'MOYOBAMBA ', 'department_id' => '22'],
            ['id' => '2202', 'nombre_provincia' => 'BELLAVISTA ', 'department_id' => '22'],
            ['id' => '2203', 'nombre_provincia' => 'EL DORADO ', 'department_id' => '22'],
            ['id' => '2204', 'nombre_provincia' => 'HUALLAGA ', 'department_id' => '22'],
            ['id' => '2205', 'nombre_provincia' => 'LAMAS ', 'department_id' => '22'],
            ['id' => '2206', 'nombre_provincia' => 'MARISCAL CÁCERES ', 'department_id' => '22'],
            ['id' => '2207', 'nombre_provincia' => 'PICOTA ', 'department_id' => '22'],
            ['id' => '2208', 'nombre_provincia' => 'RIOJA ', 'department_id' => '22'],
            ['id' => '2209', 'nombre_provincia' => 'SAN MARTÍN ', 'department_id' => '22'],
            ['id' => '2210', 'nombre_provincia' => 'TOCACHE ', 'department_id' => '22'],
            ['id' => '2301', 'nombre_provincia' => 'TACNA ', 'department_id' => '23'],
            ['id' => '2302', 'nombre_provincia' => 'CANDARAVE ', 'department_id' => '23'],
            ['id' => '2303', 'nombre_provincia' => 'JORGE BASADRE ', 'department_id' => '23'],
            ['id' => '2304', 'nombre_provincia' => 'TARATA ', 'department_id' => '23'],
            ['id' => '2401', 'nombre_provincia' => 'TUMBES ', 'department_id' => '24'],
            ['id' => '2402', 'nombre_provincia' => 'CONTRALMIRANTE VILLAR ', 'department_id' => '24'],
            ['id' => '2403', 'nombre_provincia' => 'ZARUMILLA ', 'department_id' => '24'],
            ['id' => '2501', 'nombre_provincia' => 'CORONEL PORTILLO ', 'department_id' => '25'],
            ['id' => '2502', 'nombre_provincia' => 'ATALAYA ', 'department_id' => '25'],
            ['id' => '2503', 'nombre_provincia' => 'PADRE ABAD ', 'department_id' => '25'],
            ['id' => '2504', 'nombre_provincia' => 'PURÚS', 'department_id' => '25'],
        ];

        DB::table('ubigeo_provincia')->insert($datos);
    }
}
