<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExamValidate extends FormRequest {
    
    public function authorize(): bool {
        return true;
    }

    public function rules(): array {
        return [
            'dni' 		            => 'required|string',
            'id_tipo' 	            => 'required|integer',
            'ta'                    => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'so2'                   => 'nullable|regex:/^\d+(\.\d{1,2})?$/',
            'peso'                  => 'nullable|regex:/^\d+(\.\d{1,2})?$/',
            'talla'                 => 'nullable|regex:/^\d+(\.\d{1,2})?$/',
            'fc'                    => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'rf'                    => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'so2'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'peso'                  => 'required|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'talla'                 => 'required|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'imc'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'pym'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'typ'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'cv'                    => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'abdomen'               => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'hemolinfopoyetico'     => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'tcs'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'neurologico'           => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'hemograma'             => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'bioquimico'            => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'perfilhepatico'        => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'perfilcoagulacion'     => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'perfilreumatologico'   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'orina'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'sangre'                => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'esputo'                => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'heces'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'lcr'                   => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'citoquimico'           => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'adalp'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'paplp'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'bclp'                  => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'cgchlp'                => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'cbklp'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'bkdab'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'bkcab'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'cgchab'                => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'papab'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'bcab'                  => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'pulmon'                => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'pleurabpp'             => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'fecha_p'               => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'fecha_s'               => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'fecha_t'               => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'funcionpulmonar'       => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'medicinanuclear'       => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'plandiag'              => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'plan'                  => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
            'otros'                 => 'nullable|regex:/^(?:[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\s\/,#\-\(\)\.])+$/',
        ];
    }

    public function messages(): array {
        return [
            'dni.required'              => 'El campo DNI es requerido',
            'dni.string'                => 'El campo DNI debe ser un string',
            //'dni.digits'                => 'El campo DNI debe tener 8 dígitos',
            'id_tipo.required'          => 'El campo tipo de examen es requerido',
            'id_tipo.integer'           => 'El campo tipo de examen debe ser un número',
            'ta.regex'                  => 'El campo TA solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'fc.regex'                  => 'El campo FC solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'rf.regex'                  => 'El campo RF solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'so2.regex'                 => 'El campo SO2 solo puede contener números y decimales.',
            'peso.regex'                => 'El campo PESO solo puede contener números y decimales',
            'peso.required'             => 'El campo PESO es requerido',
            'talla.regex'               => 'El campo TALLA solo puede contener números y decimales',
            'talla.required'            => 'El campo TALLA es requerido',
            'imc.regex'                 => 'El campo IMC solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'pym.regex'                 => 'El campo PYM solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'typ.regex'                 => 'El campo TYP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'cv.regex'                  => 'El campo CV solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'abdomen.regex'             => 'El campo ABDOMEN solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'hemolinfopoyetico.regex'   => 'El campo HEMOLINFOPOYETICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'tcs.regex'                 => 'El campo TCS solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'neurologico.regex'         => 'El campo NEUROLOGICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'hemograma.regex'           => 'El campo HEMOGRAMA solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'bioquimico.regex'          => 'El campo BIOQUIMICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'perfilhepatico.regex'      => 'El campo PERFILHEPATICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'perfilcoagulacion.regex'   => 'El campo PERFILCOAGULACION solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'perfilreumatologico.regex' => 'El campo PERFILREUMATOLÓGICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'orina.regex'               => 'El campo ORINA solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'sangre.regex'              => 'El campo SANGRE solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'esputo.regex'              => 'El campo ESPUTO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'heces.regex'               => 'El campo HECES solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'lcr.regex'                 => 'El campo LCR solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'citoquimico.regex'         => 'El campo CITOQUIMICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'adalp.regex'               => 'El campo ADALP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'paplp.regex'               => 'El campo PAPLP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'bclp.regex'                => 'El campo BCLP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'cgchlp.regex'              => 'El campo CGCHLP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'cbklp.regex'               => 'El campo CBKLP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'bkdab.regex'               => 'El campo BKDAB solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'bkcab.regex'               => 'El campo BKCAB solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'cgchab.regex'              => 'El campo CGCHAB solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'papab.regex'               => 'El campo PAPAB solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'bcab.regex'                => 'El campo BCAB solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'pulmon.regex'              => 'El campo PULMON solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'pleurabpp.regex'           => 'El campo PLEURA BPP solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'funcionpulmonar.regex'     => 'El campo FUNCION PULMONAR solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'medicinanuclear.regex'     => 'El campo MEDICINA NUCLEAR solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'plandiag.regex'            => 'El campo PLAN DIAGNOSTICO solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'plan.regex'                => 'El campo PLAN solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
            'otros.regex'               => 'El campo OTROS solo puede contener letras, números, espacios y los siguientes caracteres: /,#-()',
        ];
    }
}
