<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExamValidate extends FormRequest {
    
    public function authorize(): bool {
        return true;
    }

    public function rules(): array {
        return [
            'dni' 		            => 'required|string|digits:8',
            'id_tipo' 	            => 'required|integer',
            'so2'                   => 'numeric|nullable|regex:/^\d+(\.\d{1,2})?$/',
            'peso'                  => 'numeric|nullable|regex:/^\d+(\.\d{1,2})?$/',
            'talla'                 => 'numeric|nullable|regex:/^\d+(\.\d{1,2})?$/',
            'ta'                    => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fc'                    => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'rf'                    => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'so2'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'peso'                  => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'talla'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'imc'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'pym'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'typ'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'cv'                    => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'abdomen'               => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'hemolinfopoyetico'     => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'tcs'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'neurologico'           => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'hemograma'             => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'bioquimico'            => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'perfilhepatico'        => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'perfilcoagulacion'     => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'perfilreumatologico'   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'orina'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'sangre'                => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'esputo'                => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'heces'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'lcr'                   => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'citoquimico'           => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'adalp'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'paplp'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'bclp'                  => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'cgchlp'                => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'cbklp'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'bkdab'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'bkcab'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'cgchab'                => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'papab'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'bcab'                  => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'pulmon'                => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'pleurabpp'             => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fecha_p'               => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fecha_s'               => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'fecha_t'               => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'funcionpulmonar'       => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'medicinanuclear'       => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'plandiag'              => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'plan'                  => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
            'otros'                 => 'string|nullable|regex:/^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\s.,-]+$/',
        ];
    }

    public function messages(): array {
        return [
            'dni.required'              => 'El campo DNI es requerido',
            'dni.string'                => 'El campo DNI debe ser un string',
            'dni.digits'                => 'El campo DNI debe tener 8 dígitos',
            'id_tipo.required'          => 'El campo tipo de examen es requerido',
            'peso.numeric'              => 'El campo peso debe ser un número',
            'talla.numeric'             => 'El campo talla debe ser un número',
            'ta.string'                 => 'El campo TA debe ser un string',
            'fc.string'                 => 'El campo FC debe ser un string',
            'rf.string'                 => 'El campo RF debe ser un string',
            'so2.numeric'               => 'El campo SO2 debe ser un número',
            'imc.string'                => 'El campo IMC debe ser un string',
            'pym.string'                => 'El campo PYM debe ser un string',
            'typ.string'                => 'El campo TYP debe ser un string',
            'cv.string'                 => 'El campo CV debe ser un string',
            'abdomen.string'            => 'El campo ABDOMEN debe ser un string',
            'hemolinfopoyetico.string'  => 'El campo HEMOLINFOPOYETICO debe ser un string',
            'hemolinfopoyetico.regex'   => 'El campo HEMOLINFOPOYETICO solo puede contener letras, números y espacios',
            'tcs.string'                => 'El campo TCS debe ser un string',
            'tcs.regex'                 => 'El campo TCS solo puede contener letras, números y espacios',
            'neurologico.string'        => 'El campo NEUROLOGICO debe ser un string',
            'neurologico.regex'         => 'El campo NEUROLOGICO solo puede contener letras, números y espacios',
            'hemograma.string'          => 'El campo HEMOGRAMA debe ser un string',
            'hemograma.regex'           => 'El campo HEMOGRAMA solo puede contener letras, números y espacios',
            'bioquimico.string'         => 'El campo BIOQUIMICO debe ser un string',
            'bioquimico.regex'          => 'El campo BIOQUIMICO solo puede contener letras, números y espacios',
            'perfilhepatico.string'     => 'El campo PERFILHEPATICO debe ser un string',
            'perfilhepatico.regex'      => 'El campo PERFILHEPATICO solo puede contener letras, números y espacios',
            'perfilhepatico.string'     => 'El campo PERFILHEPATICO debe ser un string',
            'perfilcoagulacion.string'  => 'El campo PERFILCOAGULACION debe ser un string',
            'perfilcoagulacion.regex'   => 'El campo PERFILCOAGULACION solo puede contener letras, números y espacios',
            'perfilcoagulacion.string'  => 'El campo PERFILCOAGULACION debe ser un string',
            'perfilreumatologico.regex' => 'El campo PERFILREUMATOLÓGICO solo puede contener letras, números y espacios',
            'perfilreumatologico.string' => 'El campo PERFILREUMATOLÓGICO debe ser un string',
            'orina.string'              => 'El campo Orina debe ser un string',
            'orina.regex'               => 'El campo Orina solo puede contener letras, números, puntos, comas y guiones.',
            'sangre.string'             => 'El campo Sangre debe ser un string',
            'sangre.regex'              => 'El campo Sangre solo puede contener letras, números, puntos, comas y guiones.',
            'esputo.string'             => 'El campo Esputo debe ser un string',
            'esputo.regex'              => 'El campo Esputo solo puede contener letras, números, puntos, comas y guiones.',
            'heces.string'              => 'El campo Heces debe ser un string',
            'heces.regex'               => 'El campo Heces solo puede contener letras, números, puntos, comas y guiones.',
            'lcr.string'                => 'El campo LCR debe ser un string',
            'lcr.regex'                 => 'El campo LCR solo puede contener letras, números, puntos, comas y guiones.',
            'citoquimico.string'        => 'El campo CITOQUIMICO debe ser un string',
            'citoquimico.regex'         => 'El campo CITOQUIMICO solo puede contener letras, números, puntos, comas y guiones.',
            'adalp.string'              => 'El campo ADALP debe ser un string',
            'adalp.regex'               => 'El campo ADALP solo puede contener letras, números, puntos, comas y guiones.',
            'paplp.string'              => 'El campo PAPLP deber ser un string',
            'paplp.regex'               => 'El campo PAPLP solo puede contener letras, números, puntos, comas y guiones.',
            'bclp.string'               => 'El campo BCLP deber ser un string',
            'bclp.regex'                => 'El campo BCLP solo puede contener letras, números, puntos, comas y guiones.',
            'cgchlp.string'             => 'El campo CGCHLP deber ser un string',
            'cgchlp.regex'              => 'El campo CGCHLP solo puede contener letras, números, puntos, comas y guiones.',
            'cbklp.string'              => 'El campo CBKLP deber ser un string',
            'cbklp.regex'               => 'El campo CBKLP solo puede contener letras, números, puntos, comas y guiones.',
            'bkdab.string'              => 'El campo BKDAB deber ser un string',
            'bkdab.regex'               => 'El campo BKDAB solo puede contener letras, números, puntos, comas y guiones.',
            'bkcab.string'              => 'El campo BKCAB deber ser un string',
            'bkcab.regex'               => 'El campo BKCAB solo puede contener letras, números, puntos, comas y guiones.',
            'cgchab.string'             => 'El campo CGCHAB deber ser un string',
            'cgchab.regex'              => 'El campo CGCHAB solo puede contener letras, números, puntos, comas y guiones.',
            'papab.string'              => 'El campo PAPAB deber ser un string',
            'papab.regex'               => 'El campo PAPAB solo puede contener letras, números, puntos, comas y guiones.',
            'bcab.string'               => 'El campo BCAB deber ser un string',
            'bcab.regex'                => 'El campo BCAB solo puede contener letras, números, puntos, comas y guiones.',
            'pulmon.string'             => 'El campo PULMON debe ser un string',
            'pulmon.regex'              => 'El campo PULMON solo puede contener letras, números, puntos, comas y guiones.',
            'pleurabpp.string'          => 'El campo PLEURABPP debe ser un string',
            'pleurabpp.regex'           => 'El campo PLEURABPP solo puede contener letras, números, puntos, comas y guiones.',
            'funcionpulmonar.string'    => 'El campo FUNCIONPULMONAR debe ser un string',
            'funcionpulmonar.regex'     => 'El campo FUNCIONPULMONAR solo puede contener letras, números, puntos, comas y guiones.',
            'medicinanuclear.string'    => 'El campo MEDICINANUCLEAR debe ser un string',
            'medicinanuclear.regex'     => 'El campo MEDICINANUCLEAR solo puede contener letras, números, puntos, comas y guiones.',
            'plandiag.string'           => 'El campo PLANDIAG debe ser un string',
            'plandiag.regex'            => 'El campo PLANDIAG solo puede contener letras, números, puntos, comas y guiones.',
            'plan.string'               => 'El campo PLAN debe ser un string',
            'plan.regex'                => 'El campo PLAN solo puede contener letras, números, puntos, comas y guiones.',
            'otros.string'              => 'El campo OTROS debe ser un string',
            'otros.regex'               => 'El campo OTROS solo puede contener letras, números, puntos, comas y guiones.',
        ];
    }

    public function prepareForValidation() {
        $this->merge([
            'dni'       => strtoupper($this->dni),
            'id_tipo'   => intval($this->id_tipo),
            'so2'       => floatval($this->so2),
            'peso'      => floatval($this->peso),
            'talla'     => floatval($this->talla),  
            
        ]);
    }
}
